// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Data;

namespace Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200701161051_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ATENDIMENTO")
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Models.Guia", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GUIA_ID")
                        .HasColumnType("decimal(18,0)")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GUIA_DATA")
                        .HasColumnType("date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("Deletada")
                        .HasColumnName("GUIA_DELETADA")
                        .HasColumnType("bit");

                    b.Property<int>("GuiaOrigemFK")
                        .HasColumnName("GUIA_ORIGEM_ID")
                        .HasColumnType("int");

                    b.Property<int>("GuiaStatusFK")
                        .HasColumnName("GUIA_STATUS_ID")
                        .HasColumnType("int");

                    b.Property<int>("GuiaTipoFK")
                        .HasColumnName("GUIA_TIPO_ID")
                        .HasColumnType("int");

                    b.Property<string>("GuiaXML")
                        .HasColumnName("GUIA_XML")
                        .HasColumnType("varchar(max)");

                    b.Property<decimal?>("LoteId")
                        .HasColumnName("LOTE_ID")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("PushId")
                        .HasColumnName("GUIA_TOKEN")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StatusCheckInFK")
                        .HasColumnName("GUIA_BENEFICIARIO_CHECKIN_STATUS_ID")
                        .HasColumnType("int");

                    b.Property<string>("TokenId")
                        .HasColumnName("GUIA_BENEFICIARIO_TOKEN")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<decimal>("Valor")
                        .HasColumnName("GUIA_VALOR")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GuiaOrigemFK");

                    b.HasIndex("GuiaStatusFK");

                    b.HasIndex("GuiaTipoFK");

                    b.HasIndex("StatusCheckInFK");

                    b.ToTable("GUIA");
                });

            modelBuilder.Entity("Domain.Models.GuiaOrigem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GUIA_ORIGEM_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("GUIA_ORIGEM_DESCRICAO")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("GUIA_ORIGEM");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "URL"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "PORTAL"
                        });
                });

            modelBuilder.Entity("Domain.Models.GuiaStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GUIA_STATUS_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("GUIA_STATUS_DESCRICAO")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("GUIA_STATUS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "ABERTA"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "FECHADA"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "NÃO VALIDADA"
                        });
                });

            modelBuilder.Entity("Domain.Models.GuiaStatusCheckIns", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BENEFICIARIO_CHECKIN_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("BENEFICIARIO_CHECKIN_DESCRICAO")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("BENEFICIARIO_CHECKIN_STATUS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "VALIDADO"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "NÃO VALIDADO"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "NÃO RESPONDEU A TEMPO - TIMEOUT"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "ATENDIMENTO MENOR - ACOMPANHANTE SEM PLANO"
                        });
                });

            modelBuilder.Entity("Domain.Models.GuiaTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GUIA_TIPO_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("GUIA_TIPO_DESCRICAO")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("Local")
                        .HasColumnName("GUIA_TIPO_LOCAL")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GUIA_TIPO");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "SP-SATD",
                            Local = 0
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "RESUMO INTERNAÇÃO",
                            Local = 0
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "HONORÁRIOS",
                            Local = 0
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "CONSULTA",
                            Local = 0
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "ODONTOLOGIA",
                            Local = 0
                        });
                });

            modelBuilder.Entity("Domain.Models.Guia", b =>
                {
                    b.HasOne("Domain.Models.GuiaOrigem", "GuiaOrigem")
                        .WithMany("Guias")
                        .HasForeignKey("GuiaOrigemFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.GuiaStatus", "GuiaStatus")
                        .WithMany("Guias")
                        .HasForeignKey("GuiaStatusFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.GuiaTipo", "GuiaTipo")
                        .WithMany("Guias")
                        .HasForeignKey("GuiaTipoFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.GuiaStatusCheckIns", "GuiaStatusCheckIns")
                        .WithMany("Guias")
                        .HasForeignKey("StatusCheckInFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Beneficiario", "Beneficiario", b1 =>
                        {
                            b1.Property<decimal>("GuiaId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("decimal(18,0)")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Cartao")
                                .IsRequired()
                                .HasColumnName("GUIA_BENEFICIARIO_CARTAO")
                                .HasColumnType("varchar(50)")
                                .HasMaxLength(50);

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnName("GUIA_BENEFICIARIO")
                                .HasColumnType("varchar(100)")
                                .HasMaxLength(100);

                            b1.HasKey("GuiaId");

                            b1.ToTable("GUIA");

                            b1.WithOwner()
                                .HasForeignKey("GuiaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.GuiaNumero", "GuiaNumero", b1 =>
                        {
                            b1.Property<decimal>("GuiaId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("decimal(18,0)")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnName("GUIA_NUMERO")
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("NumeroOperadora")
                                .IsRequired()
                                .HasColumnName("GUIA_NUMERO_OPERADORA")
                                .HasColumnType("varchar(50)");

                            b1.HasKey("GuiaId");

                            b1.ToTable("GUIA");

                            b1.WithOwner()
                                .HasForeignKey("GuiaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Prestador", "Prestador", b1 =>
                        {
                            b1.Property<decimal>("GuiaId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("decimal(18,0)")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasColumnName("PRESTADOR_ID")
                                .HasColumnType("varchar(50)");

                            b1.Property<int?>("LoginId")
                                .HasColumnName("PRESTADOR_LOGIN_ID")
                                .HasColumnType("int");

                            b1.HasKey("GuiaId");

                            b1.ToTable("GUIA");

                            b1.WithOwner()
                                .HasForeignKey("GuiaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Unidade", "Unidade", b1 =>
                        {
                            b1.Property<decimal>("GuiaId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("decimal(18,0)")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Id")
                                .HasColumnName("PRESTADOR_UNIDADE_ID")
                                .HasColumnType("varchar(50)");

                            b1.HasKey("GuiaId");

                            b1.ToTable("GUIA");

                            b1.WithOwner()
                                .HasForeignKey("GuiaId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
